# Generated by Django 2.2.6 on 2019-11-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191105_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, null=True, unique=True),
        ),
    ]
